### ISSUE TITLE
Lifetimes are anon

### ISSUE THREAD

**Issue by gilescope** [paritytech/scale-decode#8]
The liftimes to the str and the &[u8;32] are all anon. If they were `'scale` (i.e. linked back to the original scale `&'scale [u8]` slice) then people could use the visitor to do zero copy decodes.

https://github.com/paritytech/scale-decode/blob/f3b7276a6e62a8f8e6d40a831dfc3fb24bfafe8c/src/visitor/str.rs#L44

https://github.com/paritytech/scale-decode/blob/f3b7276a6e62a8f8e6d40a831dfc3fb24bfafe8c/src/visitor/mod.rs#L75

**Comment by jsdw** [comment]
This will be closed by #11, which uses a touch og GATs to allow zero copy decoding.
